/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[12] = {4, 3, 0, 2, 5, 6, 1, 3, 0, 2, 3, 2};
static const casadi_int casadi_s3[11] = {4, 3, 0, 3, 4, 5, 0, 1, 3, 1, 2};
static const casadi_int casadi_s4[6] = {4, 1, 0, 2, 1, 3};
static const casadi_int casadi_s5[6] = {4, 1, 0, 2, 2, 3};

/* asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z:(i0[3],i1[3],i2,i3,i4)->(o0[4x3,6nz],o1[4x3,5nz],o2[4x1,2nz],o3[4x1,2nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a5, a6, a7, a8, a9;
  a0=4.;
  if (res[0]!=0) res[0][0]=a0;
  a0=5.0000000000000000e-01;
  a1=arg[0]? arg[0][1] : 0;
  a2=1.0000000000000000e-10;
  a3=(a1/a2);
  a3=tanh(a3);
  a4=(a0*a3);
  a4=(a0+a4);
  a5=9.9999999999999978e-02;
  a6=1.;
  a7=-4.5000000000000001e-01;
  a8=arg[4]? arg[4][0] : 0;
  a7=(a7*a8);
  a7=exp(a7);
  a7=(a6-a7);
  a8=(a5*a7);
  a9=7.1999999999999995e-02;
  a10=casadi_sq(a1);
  a10=(a10+a2);
  a10=sqrt(a10);
  a11=(a9*a10);
  a12=2.2280000000000002e+00;
  a13=-4.;
  a14=arg[0]? arg[0][0] : 0;
  a15=(a13*a14);
  a16=6.;
  a17=arg[1]? arg[1][0] : 0;
  a17=(a16*a17);
  a15=(a15-a17);
  a17=arg[2]? arg[2][0] : 0;
  a15=(a15+a17);
  a17=(a12*a15);
  a18=casadi_sq(a17);
  a18=(a18+a2);
  a18=sqrt(a18);
  a19=(a18+a6);
  a11=(a11/a19);
  a20=(-a11);
  a20=exp(a20);
  a21=9.0000000000000002e-01;
  a22=(a21*a7);
  a22=(a20*a22);
  a14=(a14*a7);
  a21=(a21*a14);
  a23=(a11/a19);
  a24=-8.9120000000000008e+00;
  a25=(a17+a17);
  a24=(a24*a25);
  a25=(a18+a18);
  a24=(a24/a25);
  a23=(a23*a24);
  a23=(a20*a23);
  a23=(a21*a23);
  a22=(a22+a23);
  a8=(a8+a22);
  a22=-1.0000000000000000e-02;
  a23=1.8559999999999999e-01;
  a24=(a23*a15);
  a25=casadi_sq(a24);
  a25=(a25+a2);
  a25=sqrt(a25);
  a26=exp(a25);
  a27=(a6-a26);
  a27=(a22*a27);
  a28=-40000000000.;
  a29=(a15/a2);
  a29=tanh(a29);
  a30=casadi_sq(a29);
  a30=(a6-a30);
  a28=(a28*a30);
  a28=(a0*a28);
  a28=(a27*a28);
  a30=(a0*a29);
  a30=(a0+a30);
  a31=-7.4239999999999995e-01;
  a32=(a24+a24);
  a31=(a31*a32);
  a32=(a25+a25);
  a31=(a31/a32);
  a31=(a26*a31);
  a31=(a22*a31);
  a31=(a30*a31);
  a28=(a28-a31);
  a8=(a8+a28);
  a8=(a4*a8);
  a28=(a1/a2);
  a28=(-a28);
  a28=tanh(a28);
  a31=(a0*a28);
  a31=(a0+a31);
  a32=(a0*a7);
  a33=-5.0000000000000000e-01;
  a34=(a33*a14);
  a35=1.5489999999999999e+00;
  a36=casadi_sq(a1);
  a36=(a36+a2);
  a36=sqrt(a36);
  a37=(a35*a36);
  a38=casadi_sq(a15);
  a38=(a38+a2);
  a38=sqrt(a38);
  a39=5.0000000000000001e-03;
  a39=(a38+a39);
  a37=(a37/a39);
  a40=(-a37);
  a40=exp(a40);
  a41=(a34*a40);
  a42=40000000000.;
  a43=(a15/a2);
  a43=(-a43);
  a43=tanh(a43);
  a44=casadi_sq(a43);
  a44=(a6-a44);
  a42=(a42*a44);
  a42=(a41*a42);
  a33=(a33*a7);
  a33=(a40*a33);
  a7=(a37/a39);
  a44=(a15+a15);
  a13=(a13*a44);
  a44=(a38+a38);
  a13=(a13/a44);
  a7=(a7*a13);
  a7=(a40*a7);
  a7=(a34*a7);
  a33=(a33+a7);
  a33=(a43*a33);
  a42=(a42+a33);
  a32=(a32+a42);
  a32=(a31*a32);
  a8=(a8+a32);
  a8=(-a8);
  if (res[0]!=0) res[0][1]=a8;
  a8=-1.;
  if (res[0]!=0) res[0][2]=a8;
  a32=2.0050000000000001e+01;
  a42=arg[0]? arg[0][2] : 0;
  a33=casadi_sq(a1);
  a33=(a33+a2);
  a33=sqrt(a33);
  a2=(a1/a33);
  a2=(a42*a2);
  a7=arg[3]? arg[3][0] : 0;
  a13=9.9999999999999995e-07;
  a7=(a7+a13);
  a2=(a2/a7);
  a2=(a6-a2);
  a2=(a32*a2);
  a2=(-a2);
  if (res[0]!=0) res[0][3]=a2;
  a5=(a5*a14);
  a2=(a21*a20);
  a5=(a5+a2);
  a2=(a30*a27);
  a5=(a5+a2);
  a2=10000000000.;
  a3=casadi_sq(a3);
  a3=(a6-a3);
  a3=(a2*a3);
  a3=(a0*a3);
  a5=(a5*a3);
  a10=(a1/a10);
  a9=(a9*a10);
  a9=(a9/a19);
  a9=(a20*a9);
  a9=(a21*a9);
  a9=(a4*a9);
  a5=(a5-a9);
  a14=(a0*a14);
  a9=(a43*a41);
  a14=(a14+a9);
  a9=-10000000000.;
  a28=casadi_sq(a28);
  a28=(a6-a28);
  a28=(a9*a28);
  a28=(a0*a28);
  a14=(a14*a28);
  a1=(a1/a36);
  a35=(a35*a1);
  a35=(a35/a39);
  a35=(a40*a35);
  a35=(a34*a35);
  a35=(a43*a35);
  a35=(a31*a35);
  a14=(a14-a35);
  a5=(a5+a14);
  a5=(-a5);
  if (res[0]!=0) res[0][4]=a5;
  a5=(a33/a7);
  a5=(a32*a5);
  if (res[0]!=0) res[0][5]=a5;
  if (res[1]!=0) res[1][0]=a6;
  if (res[1]!=0) res[1][1]=a16;
  a16=(a11/a19);
  a5=-1.3368000000000002e+01;
  a14=(a17+a17);
  a5=(a5*a14);
  a14=(a18+a18);
  a5=(a5/a14);
  a16=(a16*a5);
  a16=(a20*a16);
  a16=(a21*a16);
  a5=-60000000000.;
  a14=casadi_sq(a29);
  a14=(a6-a14);
  a5=(a5*a14);
  a5=(a0*a5);
  a5=(a27*a5);
  a14=-1.1135999999999999e+00;
  a35=(a24+a24);
  a14=(a14*a35);
  a35=(a25+a25);
  a14=(a14/a35);
  a14=(a26*a14);
  a14=(a22*a14);
  a14=(a30*a14);
  a5=(a5-a14);
  a16=(a16+a5);
  a16=(a4*a16);
  a5=60000000000.;
  a14=casadi_sq(a43);
  a14=(a6-a14);
  a5=(a5*a14);
  a5=(a41*a5);
  a14=(a37/a39);
  a35=-6.;
  a1=(a15+a15);
  a35=(a35*a1);
  a1=(a38+a38);
  a35=(a35/a1);
  a14=(a14*a35);
  a14=(a40*a14);
  a14=(a34*a14);
  a14=(a43*a14);
  a5=(a5+a14);
  a5=(a31*a5);
  a16=(a16+a5);
  a16=(-a16);
  if (res[1]!=0) res[1][2]=a16;
  if (res[1]!=0) res[1][3]=a6;
  if (res[1]!=0) res[1][4]=a6;
  if (res[2]!=0) res[2][0]=a8;
  a11=(a11/a19);
  a17=(a17+a17);
  a12=(a12*a17);
  a18=(a18+a18);
  a12=(a12/a18);
  a11=(a11*a12);
  a20=(a20*a11);
  a21=(a21*a20);
  a29=casadi_sq(a29);
  a29=(a6-a29);
  a2=(a2*a29);
  a0=(a0*a2);
  a27=(a27*a0);
  a24=(a24+a24);
  a23=(a23*a24);
  a25=(a25+a25);
  a23=(a23/a25);
  a26=(a26*a23);
  a22=(a22*a26);
  a30=(a30*a22);
  a27=(a27-a30);
  a21=(a21+a27);
  a4=(a4*a21);
  a21=casadi_sq(a43);
  a21=(a6-a21);
  a9=(a9*a21);
  a41=(a41*a9);
  a37=(a37/a39);
  a15=(a15/a38);
  a37=(a37*a15);
  a40=(a40*a37);
  a34=(a34*a40);
  a43=(a43*a34);
  a41=(a41+a43);
  a31=(a31*a41);
  a4=(a4+a31);
  a4=(-a4);
  if (res[2]!=0) res[2][1]=a4;
  a42=(a42*a33);
  a42=(a42/a7);
  a42=(a42/a7);
  a32=(a32*a42);
  a32=(-a32);
  if (res[3]!=0) res[3][0]=a32;
  if (res[3]!=0) res[3][1]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int asymmetric_hysteresis_model_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
