/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hysteresis_model_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[9] = {3, 2, 0, 3, 4, 0, 1, 2, 1};
static const casadi_int casadi_s4[7] = {3, 2, 0, 1, 2, 0, 1};
static const casadi_int casadi_s5[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s6[5] = {3, 1, 0, 1, 2};

/* hysteresis_model_impl_dae_jac_x_xdot_u_z:(i0[2],i1[2],i2,i3,i4[])->(o0[3x2,4nz],o1[3x2,2nz],o2[3],o3[3x1,1nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=3.3333333333333331e-01;
  if (res[0]!=0) res[0][0]=a0;
  a1=7.;
  a2=-3.3333333333333331e-01;
  a3=arg[0]? arg[0][1] : 0;
  a4=casadi_sq(a3);
  a5=1.0000000000000000e-08;
  a4=(a4+a5);
  a6=sqrt(a4);
  a7=(a6*a4);
  a8=20.;
  a9=arg[2]? arg[2][0] : 0;
  a10=arg[0]? arg[0][0] : 0;
  a9=(a9-a10);
  a9=(a0*a9);
  a11=(a9+a9);
  a11=(a2*a11);
  a12=casadi_sq(a9);
  a12=(a12+a5);
  a12=sqrt(a12);
  a13=(a12+a12);
  a11=(a11/a13);
  a11=(a8*a11);
  a11=(a3*a11);
  a11=(a7*a11);
  a11=(a2-a11);
  a13=-6.3333333333333330e+00;
  a14=casadi_sq(a3);
  a14=(a14+a5);
  a15=casadi_sq(a14);
  a13=(a13*a15);
  a11=(a11-a13);
  a11=(a1*a11);
  a11=(-a11);
  if (res[0]!=0) res[0][1]=a11;
  a11=5.9343034025940089e-01;
  a10=(a11*a10);
  a13=(a9+a9);
  a13=(a2*a13);
  a16=casadi_sq(a9);
  a16=(a16+a5);
  a16=sqrt(a16);
  a17=(a16+a16);
  a13=(a13/a17);
  a13=(a10*a13);
  a17=(a11*a16);
  a13=(a13+a17);
  a17=(a9+a9);
  a17=(a2*a17);
  a18=casadi_sq(a9);
  a18=(a18+a5);
  a18=sqrt(a18);
  a5=(a18+a18);
  a17=(a17/a5);
  a17=(a10*a17);
  a11=(a11*a18);
  a17=(a17+a11);
  a13=(a13+a17);
  a13=(-a13);
  if (res[0]!=0) res[0][2]=a13;
  a13=(a8*a12);
  a17=(a7*a13);
  a13=(a13*a3);
  a11=(a3/a6);
  a4=(a4*a11);
  a11=(a3+a3);
  a6=(a6*a11);
  a4=(a4+a6);
  a13=(a13*a4);
  a17=(a17+a13);
  a13=19.;
  a13=(a13*a9);
  a14=(a14+a14);
  a4=(a3+a3);
  a14=(a14*a4);
  a13=(a13*a14);
  a17=(a17+a13);
  a17=(a1*a17);
  if (res[0]!=0) res[0][3]=a17;
  a17=1.;
  if (res[1]!=0) res[1][0]=a17;
  if (res[1]!=0) res[1][1]=a17;
  if (res[2]!=0) res[2][0]=a2;
  a2=(a9+a9);
  a2=(a0*a2);
  a12=(a12+a12);
  a2=(a2/a12);
  a8=(a8*a2);
  a3=(a3*a8);
  a7=(a7*a3);
  a7=(a0-a7);
  a3=6.3333333333333330e+00;
  a3=(a3*a15);
  a7=(a7-a3);
  a1=(a1*a7);
  a1=(-a1);
  if (res[2]!=0) res[2][1]=a1;
  a1=(a9+a9);
  a1=(a0*a1);
  a16=(a16+a16);
  a1=(a1/a16);
  a1=(a10*a1);
  a9=(a9+a9);
  a0=(a0*a9);
  a18=(a18+a18);
  a0=(a0/a18);
  a10=(a10*a0);
  a1=(a1+a10);
  a1=(-a1);
  if (res[2]!=0) res[2][2]=a1;
  if (res[3]!=0) res[3][0]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int hysteresis_model_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hysteresis_model_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hysteresis_model_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hysteresis_model_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hysteresis_model_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hysteresis_model_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hysteresis_model_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void hysteresis_model_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hysteresis_model_impl_dae_jac_x_xdot_u_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int hysteresis_model_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real hysteresis_model_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hysteresis_model_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hysteresis_model_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hysteresis_model_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hysteresis_model_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hysteresis_model_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
