/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hysteresis_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};

/* hysteresis_model_expl_vde_forw:(i0[2],i1[2x2],i2[2],i3,i4[2])->(o0[2],o1[2x2],o2[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a3, a4, a5, a6, a7, a8, a9;
  a0=2.0000000000000001e-01;
  a1=arg[3]? arg[3][0] : 0;
  a2=arg[0]? arg[0][0] : 0;
  a1=(a1-a2);
  a1=(a0*a1);
  if (res[0]!=0) res[0][0]=a1;
  a2=3.;
  a3=6.9999999999999996e-01;
  a4=casadi_sq(a1);
  a5=1.0000000000000000e-08;
  a4=(a4+a5);
  a4=sqrt(a4);
  a6=(a3*a4);
  a7=arg[0]? arg[0][1] : 0;
  a8=(a6*a7);
  a9=casadi_sq(a7);
  a9=(a9+a5);
  a10=casadi_sq(a9);
  a11=(a8*a10);
  a11=(a1-a11);
  a12=-3.0000000000000004e-01;
  a13=(a12*a1);
  a14=casadi_sq(a7);
  a14=(a14+a5);
  a5=sqrt(a14);
  a15=casadi_sq(a14);
  a16=(a5*a15);
  a17=(a13*a16);
  a11=(a11-a17);
  a11=(a2*a11);
  if (res[0]!=0) res[0][1]=a11;
  a11=arg[1]? arg[1][0] : 0;
  a11=(a0*a11);
  a17=(-a11);
  if (res[1]!=0) res[1][0]=a17;
  a17=arg[1]? arg[1][1] : 0;
  a18=(a6*a17);
  a19=(a1+a1);
  a20=(a19*a11);
  a21=(a4+a4);
  a20=(a20/a21);
  a20=(a3*a20);
  a20=(a7*a20);
  a18=(a18-a20);
  a18=(a10*a18);
  a20=(a9+a9);
  a22=(a7+a7);
  a23=(a22*a17);
  a23=(a20*a23);
  a23=(a8*a23);
  a18=(a18+a23);
  a18=(a11+a18);
  a23=(a7+a7);
  a17=(a23*a17);
  a24=(a5+a5);
  a25=(a17/a24);
  a25=(a15*a25);
  a26=(a14+a14);
  a17=(a26*a17);
  a17=(a5*a17);
  a25=(a25+a17);
  a25=(a13*a25);
  a11=(a12*a11);
  a11=(a16*a11);
  a25=(a25-a11);
  a18=(a18+a25);
  a18=(a2*a18);
  a18=(-a18);
  if (res[1]!=0) res[1][1]=a18;
  a18=arg[1]? arg[1][2] : 0;
  a18=(a0*a18);
  a25=(-a18);
  if (res[1]!=0) res[1][2]=a25;
  a25=arg[1]? arg[1][3] : 0;
  a11=(a6*a25);
  a19=(a19*a18);
  a19=(a19/a21);
  a19=(a3*a19);
  a19=(a7*a19);
  a11=(a11-a19);
  a11=(a10*a11);
  a22=(a22*a25);
  a20=(a20*a22);
  a20=(a8*a20);
  a11=(a11+a20);
  a11=(a18+a11);
  a23=(a23*a25);
  a24=(a23/a24);
  a24=(a15*a24);
  a26=(a26*a23);
  a26=(a5*a26);
  a24=(a24+a26);
  a24=(a13*a24);
  a18=(a12*a18);
  a18=(a16*a18);
  a24=(a24-a18);
  a11=(a11+a24);
  a11=(a2*a11);
  a11=(-a11);
  if (res[1]!=0) res[1][3]=a11;
  a11=arg[2]? arg[2][0] : 0;
  a11=(a0*a11);
  a24=(a0-a11);
  if (res[2]!=0) res[2][0]=a24;
  a24=(a1+a1);
  a24=(a0*a24);
  a18=(a4+a4);
  a24=(a24/a18);
  a24=(a3*a24);
  a24=(a7*a24);
  a24=(a10*a24);
  a0=(a0-a24);
  a24=-6.0000000000000012e-02;
  a24=(a24*a16);
  a0=(a0-a24);
  a0=(a2*a0);
  a24=arg[2]? arg[2][1] : 0;
  a6=(a6*a24);
  a1=(a1+a1);
  a1=(a1*a11);
  a4=(a4+a4);
  a1=(a1/a4);
  a3=(a3*a1);
  a3=(a7*a3);
  a6=(a6-a3);
  a10=(a10*a6);
  a9=(a9+a9);
  a6=(a7+a7);
  a6=(a6*a24);
  a9=(a9*a6);
  a8=(a8*a9);
  a10=(a10+a8);
  a10=(a11+a10);
  a7=(a7+a7);
  a7=(a7*a24);
  a24=(a5+a5);
  a24=(a7/a24);
  a15=(a15*a24);
  a14=(a14+a14);
  a14=(a14*a7);
  a5=(a5*a14);
  a15=(a15+a5);
  a13=(a13*a15);
  a12=(a12*a11);
  a16=(a16*a12);
  a13=(a13-a16);
  a10=(a10+a13);
  a2=(a2*a10);
  a0=(a0-a2);
  if (res[2]!=0) res[2][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int hysteresis_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hysteresis_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hysteresis_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hysteresis_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hysteresis_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hysteresis_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hysteresis_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void hysteresis_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hysteresis_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int hysteresis_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real hysteresis_model_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hysteresis_model_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hysteresis_model_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hysteresis_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hysteresis_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hysteresis_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
