/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hysteresis_model_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[9] = {3, 2, 0, 3, 4, 0, 1, 2, 1};
static const casadi_int casadi_s5[7] = {3, 2, 0, 1, 2, 0, 1};

/* hysteresis_model_impl_dae_fun_jac_x_xdot_u:(i0[2],i1[2],i2,i3,i4[])->(o0[3],o1[3x2,4nz],o2[3x2,2nz],o3[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=3.3333333333333331e-01;
  a2=arg[2]? arg[2][0] : 0;
  a3=arg[0]? arg[0][0] : 0;
  a4=(a2-a3);
  a4=(a1*a4);
  a0=(a0-a4);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a5=3.;
  a6=6.9999999999999996e-01;
  a7=casadi_sq(a4);
  a8=1.0000000000000000e-10;
  a7=(a7+a8);
  a7=sqrt(a7);
  a9=(a6*a7);
  a10=arg[0]? arg[0][1] : 0;
  a11=(a9*a10);
  a12=casadi_sq(a10);
  a12=(a12+a8);
  a13=sqrt(a12);
  a14=(a13*a12);
  a15=(a11*a14);
  a15=(a4-a15);
  a16=-3.0000000000000004e-01;
  a16=(a16*a4);
  a17=casadi_sq(a10);
  a17=(a17+a8);
  a18=casadi_sq(a17);
  a19=(a16*a18);
  a15=(a15-a19);
  a15=(a5*a15);
  a0=(a0-a15);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[3]? arg[3][0] : 0;
  a15=5.0000000000000000e-01;
  a19=(a4/a8);
  a19=tanh(a19);
  a20=(a15*a19);
  a20=(a15+a20);
  a21=9.0000000000000002e-01;
  a22=5.9343034025940089e-01;
  a22=(a22*a3);
  a3=(a21*a22);
  a23=1.0000000000000001e-01;
  a24=(a23*a22);
  a25=casadi_sq(a2);
  a25=(a25+a8);
  a25=sqrt(a25);
  a26=(-a25);
  a26=exp(a26);
  a27=(a24*a26);
  a3=(a3+a27);
  a27=(a20*a3);
  a28=(a4/a8);
  a28=(-a28);
  a28=tanh(a28);
  a29=(a15*a28);
  a29=(a15+a29);
  a30=9.9999999999999978e-02;
  a30=(a30*a22);
  a21=(a21*a22);
  a22=casadi_sq(a2);
  a22=(a22+a8);
  a22=sqrt(a22);
  a8=(-a22);
  a8=exp(a8);
  a31=(a21*a8);
  a30=(a30+a31);
  a31=(a29*a30);
  a27=(a27+a31);
  a0=(a0-a27);
  if (res[0]!=0) res[0][2]=a0;
  if (res[1]!=0) res[1][0]=a1;
  a0=-3.3333333333333331e-01;
  a27=(a4+a4);
  a27=(a0*a27);
  a31=(a7+a7);
  a27=(a27/a31);
  a27=(a6*a27);
  a27=(a10*a27);
  a27=(a14*a27);
  a27=(a0-a27);
  a23=(a23*a18);
  a27=(a27-a23);
  a27=(a5*a27);
  a27=(-a27);
  if (res[1]!=0) res[1][1]=a27;
  a27=-3.3333333333333330e+09;
  a23=1.;
  a31=casadi_sq(a19);
  a31=(a23-a31);
  a31=(a27*a31);
  a31=(a15*a31);
  a31=(a3*a31);
  a32=5.3408730623346079e-01;
  a33=5.9343034025940093e-02;
  a33=(a33*a26);
  a33=(a32+a33);
  a33=(a20*a33);
  a31=(a31+a33);
  a33=3.3333333333333330e+09;
  a34=casadi_sq(a28);
  a34=(a23-a34);
  a34=(a33*a34);
  a34=(a15*a34);
  a34=(a30*a34);
  a35=5.9343034025940079e-02;
  a32=(a32*a8);
  a35=(a35+a32);
  a35=(a29*a35);
  a34=(a34+a35);
  a31=(a31+a34);
  a31=(-a31);
  if (res[1]!=0) res[1][2]=a31;
  a9=(a14*a9);
  a31=(a10/a13);
  a12=(a12*a31);
  a31=(a10+a10);
  a13=(a13*a31);
  a12=(a12+a13);
  a11=(a11*a12);
  a9=(a9+a11);
  a17=(a17+a17);
  a11=(a10+a10);
  a17=(a17*a11);
  a16=(a16*a17);
  a9=(a9+a16);
  a9=(a5*a9);
  if (res[1]!=0) res[1][3]=a9;
  if (res[2]!=0) res[2][0]=a23;
  if (res[2]!=0) res[2][1]=a23;
  if (res[3]!=0) res[3][0]=a0;
  a4=(a4+a4);
  a4=(a1*a4);
  a7=(a7+a7);
  a4=(a4/a7);
  a6=(a6*a4);
  a10=(a10*a6);
  a14=(a14*a10);
  a1=(a1-a14);
  a14=-1.0000000000000001e-01;
  a14=(a14*a18);
  a1=(a1-a14);
  a5=(a5*a1);
  a5=(-a5);
  if (res[3]!=0) res[3][1]=a5;
  a19=casadi_sq(a19);
  a19=(a23-a19);
  a33=(a33*a19);
  a33=(a15*a33);
  a3=(a3*a33);
  a25=(a2/a25);
  a26=(a26*a25);
  a24=(a24*a26);
  a20=(a20*a24);
  a3=(a3-a20);
  a28=casadi_sq(a28);
  a23=(a23-a28);
  a27=(a27*a23);
  a15=(a15*a27);
  a30=(a30*a15);
  a2=(a2/a22);
  a8=(a8*a2);
  a21=(a21*a8);
  a29=(a29*a21);
  a30=(a30-a29);
  a3=(a3+a30);
  a3=(-a3);
  if (res[3]!=0) res[3][2]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int hysteresis_model_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hysteresis_model_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hysteresis_model_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hysteresis_model_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hysteresis_model_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hysteresis_model_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hysteresis_model_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void hysteresis_model_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hysteresis_model_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int hysteresis_model_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real hysteresis_model_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hysteresis_model_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hysteresis_model_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hysteresis_model_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hysteresis_model_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hysteresis_model_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
