/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[24] = {20, 1, 0, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
static const casadi_int casadi_s5[73] = {20, 15, 0, 3, 8, 13, 18, 22, 26, 31, 36, 41, 45, 47, 49, 51, 53, 55, 5, 6, 15, 5, 6, 7, 15, 16, 6, 7, 8, 16, 17, 7, 8, 9, 17, 18, 8, 9, 18, 19, 0, 5, 6, 10, 1, 5, 6, 7, 11, 2, 6, 7, 8, 12, 3, 7, 8, 9, 13, 4, 8, 9, 14, 5, 10, 6, 11, 7, 12, 8, 13, 9, 14};
static const casadi_int casadi_s6[33] = {20, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s7[18] = {20, 5, 0, 2, 4, 6, 8, 10, 10, 15, 11, 16, 12, 17, 13, 18, 14, 19};

/* mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z:(i0[15],i1[15],i2,i3[5],i4[2])->(o0[20],o1[20x15,55nz],o2[20x15,15nz],o3[20x5,10nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][5] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a2=arg[0]? arg[0][6] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a3=arg[0]? arg[0][7] : 0;
  a0=(a0-a3);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a4=arg[0]? arg[0][8] : 0;
  a0=(a0-a4);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a5=arg[0]? arg[0][9] : 0;
  a0=(a0-a5);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][5] : 0;
  a6=8.5018666181568042e+04;
  a7=-100.;
  a7=(a7*a1);
  a8=100.;
  a9=(a8*a2);
  a7=(a7+a9);
  a9=arg[2]? arg[2][0] : 0;
  a10=8.4823001646924400e+04;
  a11=arg[0]? arg[0][0] : 0;
  a12=(a10*a11);
  a13=-8.4823001646924400e+04;
  a14=arg[0]? arg[0][1] : 0;
  a15=(a13*a14);
  a12=(a12+a15);
  a9=(a9-a12);
  a7=(a7+a9);
  a9=arg[0]? arg[0][10] : 0;
  a7=(a7-a9);
  a7=(a6*a7);
  a0=(a0-a7);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1]? arg[1][6] : 0;
  a7=(a8*a1);
  a15=-200.;
  a16=(a15*a2);
  a7=(a7+a16);
  a16=(a8*a3);
  a7=(a7+a16);
  a16=(a10*a14);
  a17=arg[0]? arg[0][2] : 0;
  a18=(a13*a17);
  a16=(a16+a18);
  a12=(a12-a16);
  a7=(a7+a12);
  a12=arg[0]? arg[0][11] : 0;
  a7=(a7-a12);
  a7=(a6*a7);
  a0=(a0-a7);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[1]? arg[1][7] : 0;
  a7=(a8*a2);
  a18=(a15*a3);
  a7=(a7+a18);
  a18=(a8*a4);
  a7=(a7+a18);
  a18=(a10*a17);
  a19=arg[0]? arg[0][3] : 0;
  a20=(a13*a19);
  a18=(a18+a20);
  a16=(a16-a18);
  a7=(a7+a16);
  a16=arg[0]? arg[0][12] : 0;
  a7=(a7-a16);
  a7=(a6*a7);
  a0=(a0-a7);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[1]? arg[1][8] : 0;
  a7=(a8*a3);
  a20=(a15*a4);
  a7=(a7+a20);
  a20=(a8*a5);
  a7=(a7+a20);
  a20=(a10*a19);
  a21=arg[0]? arg[0][4] : 0;
  a22=(a13*a21);
  a20=(a20+a22);
  a18=(a18-a20);
  a7=(a7+a18);
  a18=arg[0]? arg[0][13] : 0;
  a7=(a7-a18);
  a7=(a6*a7);
  a0=(a0-a7);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[1]? arg[1][9] : 0;
  a8=(a8*a4);
  a15=(a15*a5);
  a8=(a8+a15);
  a15=(a10*a21);
  a20=(a20-a15);
  a8=(a8+a20);
  a20=arg[0]? arg[0][14] : 0;
  a8=(a8-a20);
  a8=(a6*a8);
  a0=(a0-a8);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[1]? arg[1][10] : 0;
  a8=5500.;
  a15=casadi_sq(a1);
  a7=1.0000000000000000e-10;
  a15=(a15+a7);
  a15=sqrt(a15);
  a22=(a9*a15);
  a23=arg[3]? arg[3][0] : 0;
  a24=(a23+a7);
  a22=(a22/a24);
  a25=(a1-a22);
  a25=(a8*a25);
  a0=(a0-a25);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[1]? arg[1][11] : 0;
  a25=casadi_sq(a2);
  a25=(a25+a7);
  a25=sqrt(a25);
  a26=(a12*a25);
  a27=arg[3]? arg[3][1] : 0;
  a28=(a27+a7);
  a26=(a26/a28);
  a29=(a2-a26);
  a29=(a8*a29);
  a0=(a0-a29);
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[1]? arg[1][12] : 0;
  a29=casadi_sq(a3);
  a29=(a29+a7);
  a29=sqrt(a29);
  a30=(a16*a29);
  a31=arg[3]? arg[3][2] : 0;
  a32=(a31+a7);
  a30=(a30/a32);
  a33=(a3-a30);
  a33=(a8*a33);
  a0=(a0-a33);
  if (res[0]!=0) res[0][12]=a0;
  a0=arg[1]? arg[1][13] : 0;
  a33=casadi_sq(a4);
  a33=(a33+a7);
  a33=sqrt(a33);
  a34=(a18*a33);
  a35=arg[3]? arg[3][3] : 0;
  a36=(a35+a7);
  a34=(a34/a36);
  a37=(a4-a34);
  a37=(a8*a37);
  a0=(a0-a37);
  if (res[0]!=0) res[0][13]=a0;
  a0=arg[1]? arg[1][14] : 0;
  a37=casadi_sq(a5);
  a37=(a37+a7);
  a37=sqrt(a37);
  a38=(a20*a37);
  a39=arg[3]? arg[3][4] : 0;
  a7=(a39+a7);
  a38=(a38/a7);
  a40=(a5-a38);
  a40=(a8*a40);
  a0=(a0-a40);
  if (res[0]!=0) res[0][14]=a0;
  a11=(a11-a14);
  a11=(a10*a11);
  a0=arg[4]? arg[4][1] : 0;
  a11=(a11*a0);
  a40=arg[4]? arg[4][0] : 0;
  a11=(a11*a40);
  a41=5.;
  a11=(a11/a41);
  a23=(a23-a11);
  if (res[0]!=0) res[0][15]=a23;
  a14=(a14-a17);
  a14=(a10*a14);
  a14=(a14*a0);
  a14=(a14*a40);
  a14=(a14/a41);
  a27=(a27-a14);
  if (res[0]!=0) res[0][16]=a27;
  a17=(a17-a19);
  a17=(a10*a17);
  a17=(a17*a0);
  a17=(a17*a40);
  a17=(a17/a41);
  a31=(a31-a17);
  if (res[0]!=0) res[0][17]=a31;
  a19=(a19-a21);
  a19=(a10*a19);
  a19=(a19*a0);
  a19=(a19*a40);
  a19=(a19/a41);
  a35=(a35-a19);
  if (res[0]!=0) res[0][18]=a35;
  a21=(a10*a21);
  a21=(a21*a0);
  a21=(a21*a40);
  a21=(a21/a41);
  a39=(a39-a21);
  if (res[0]!=0) res[0][19]=a39;
  a39=7.2115384615384617e+09;
  if (res[1]!=0) res[1][0]=a39;
  a39=-7.2115384615384617e+09;
  if (res[1]!=0) res[1][1]=a39;
  a21=2.0000000000000001e-01;
  a41=(a10*a0);
  a41=(a40*a41);
  a41=(a21*a41);
  a41=(-a41);
  if (res[1]!=0) res[1][2]=a41;
  if (res[1]!=0) res[1][3]=a39;
  a41=1.4423076923076923e+10;
  if (res[1]!=0) res[1][4]=a41;
  if (res[1]!=0) res[1][5]=a39;
  a35=(a13*a0);
  a35=(a40*a35);
  a35=(a21*a35);
  a35=(-a35);
  if (res[1]!=0) res[1][6]=a35;
  a35=(a10*a0);
  a35=(a40*a35);
  a35=(a21*a35);
  a35=(-a35);
  if (res[1]!=0) res[1][7]=a35;
  if (res[1]!=0) res[1][8]=a39;
  if (res[1]!=0) res[1][9]=a41;
  if (res[1]!=0) res[1][10]=a39;
  a35=(a13*a0);
  a35=(a40*a35);
  a35=(a21*a35);
  a35=(-a35);
  if (res[1]!=0) res[1][11]=a35;
  a35=(a10*a0);
  a35=(a40*a35);
  a35=(a21*a35);
  a35=(-a35);
  if (res[1]!=0) res[1][12]=a35;
  if (res[1]!=0) res[1][13]=a39;
  if (res[1]!=0) res[1][14]=a41;
  if (res[1]!=0) res[1][15]=a39;
  a35=(a13*a0);
  a35=(a40*a35);
  a35=(a21*a35);
  a35=(-a35);
  if (res[1]!=0) res[1][16]=a35;
  a35=(a10*a0);
  a35=(a40*a35);
  a35=(a21*a35);
  a35=(-a35);
  if (res[1]!=0) res[1][17]=a35;
  if (res[1]!=0) res[1][18]=a39;
  if (res[1]!=0) res[1][19]=a41;
  a13=(a13*a0);
  a13=(a40*a13);
  a13=(a21*a13);
  a13=(-a13);
  if (res[1]!=0) res[1][20]=a13;
  a10=(a10*a0);
  a40=(a40*a10);
  a21=(a21*a40);
  a21=(-a21);
  if (res[1]!=0) res[1][21]=a21;
  a21=-1.;
  if (res[1]!=0) res[1][22]=a21;
  a40=8.5018666181568038e+06;
  if (res[1]!=0) res[1][23]=a40;
  a40=-8.5018666181568038e+06;
  if (res[1]!=0) res[1][24]=a40;
  a10=1.;
  a1=(a1/a15);
  a9=(a9*a1);
  a9=(a9/a24);
  a9=(a10-a9);
  a9=(a8*a9);
  a9=(-a9);
  if (res[1]!=0) res[1][25]=a9;
  if (res[1]!=0) res[1][26]=a21;
  if (res[1]!=0) res[1][27]=a40;
  a9=1.7003733236313608e+07;
  if (res[1]!=0) res[1][28]=a9;
  if (res[1]!=0) res[1][29]=a40;
  a2=(a2/a25);
  a12=(a12*a2);
  a12=(a12/a28);
  a12=(a10-a12);
  a12=(a8*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][30]=a12;
  if (res[1]!=0) res[1][31]=a21;
  if (res[1]!=0) res[1][32]=a40;
  if (res[1]!=0) res[1][33]=a9;
  if (res[1]!=0) res[1][34]=a40;
  a3=(a3/a29);
  a16=(a16*a3);
  a16=(a16/a32);
  a16=(a10-a16);
  a16=(a8*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][35]=a16;
  if (res[1]!=0) res[1][36]=a21;
  if (res[1]!=0) res[1][37]=a40;
  if (res[1]!=0) res[1][38]=a9;
  if (res[1]!=0) res[1][39]=a40;
  a4=(a4/a33);
  a18=(a18*a4);
  a18=(a18/a36);
  a18=(a10-a18);
  a18=(a8*a18);
  a18=(-a18);
  if (res[1]!=0) res[1][40]=a18;
  if (res[1]!=0) res[1][41]=a21;
  if (res[1]!=0) res[1][42]=a40;
  if (res[1]!=0) res[1][43]=a9;
  a5=(a5/a37);
  a20=(a20*a5);
  a20=(a20/a7);
  a20=(a10-a20);
  a20=(a8*a20);
  a20=(-a20);
  if (res[1]!=0) res[1][44]=a20;
  if (res[1]!=0) res[1][45]=a6;
  a15=(a15/a24);
  a15=(a8*a15);
  if (res[1]!=0) res[1][46]=a15;
  if (res[1]!=0) res[1][47]=a6;
  a25=(a25/a28);
  a25=(a8*a25);
  if (res[1]!=0) res[1][48]=a25;
  if (res[1]!=0) res[1][49]=a6;
  a29=(a29/a32);
  a29=(a8*a29);
  if (res[1]!=0) res[1][50]=a29;
  if (res[1]!=0) res[1][51]=a6;
  a33=(a33/a36);
  a33=(a8*a33);
  if (res[1]!=0) res[1][52]=a33;
  if (res[1]!=0) res[1][53]=a6;
  a37=(a37/a7);
  a37=(a8*a37);
  if (res[1]!=0) res[1][54]=a37;
  if (res[2]!=0) res[2][0]=a10;
  if (res[2]!=0) res[2][1]=a10;
  if (res[2]!=0) res[2][2]=a10;
  if (res[2]!=0) res[2][3]=a10;
  if (res[2]!=0) res[2][4]=a10;
  if (res[2]!=0) res[2][5]=a10;
  if (res[2]!=0) res[2][6]=a10;
  if (res[2]!=0) res[2][7]=a10;
  if (res[2]!=0) res[2][8]=a10;
  if (res[2]!=0) res[2][9]=a10;
  if (res[2]!=0) res[2][10]=a10;
  if (res[2]!=0) res[2][11]=a10;
  if (res[2]!=0) res[2][12]=a10;
  if (res[2]!=0) res[2][13]=a10;
  if (res[2]!=0) res[2][14]=a10;
  a22=(a22/a24);
  a22=(a8*a22);
  a22=(-a22);
  if (res[3]!=0) res[3][0]=a22;
  if (res[3]!=0) res[3][1]=a10;
  a26=(a26/a28);
  a26=(a8*a26);
  a26=(-a26);
  if (res[3]!=0) res[3][2]=a26;
  if (res[3]!=0) res[3][3]=a10;
  a30=(a30/a32);
  a30=(a8*a30);
  a30=(-a30);
  if (res[3]!=0) res[3][4]=a30;
  if (res[3]!=0) res[3][5]=a10;
  a34=(a34/a36);
  a34=(a8*a34);
  a34=(-a34);
  if (res[3]!=0) res[3][6]=a34;
  if (res[3]!=0) res[3][7]=a10;
  a38=(a38/a7);
  a8=(a8*a38);
  a8=(-a8);
  if (res[3]!=0) res[3][8]=a8;
  if (res[3]!=0) res[3][9]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
