/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[73] = {20, 15, 0, 3, 8, 13, 18, 22, 26, 31, 36, 41, 45, 47, 49, 51, 53, 55, 5, 6, 15, 5, 6, 7, 15, 16, 6, 7, 8, 16, 17, 7, 8, 9, 17, 18, 8, 9, 18, 19, 0, 5, 6, 10, 1, 5, 6, 7, 11, 2, 6, 7, 8, 12, 3, 7, 8, 9, 13, 4, 8, 9, 14, 5, 10, 6, 11, 7, 12, 8, 13, 9, 14};
static const casadi_int casadi_s5[33] = {20, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s6[5] = {20, 1, 0, 1, 5};
static const casadi_int casadi_s7[18] = {20, 5, 0, 2, 4, 6, 8, 10, 10, 15, 11, 16, 12, 17, 13, 18, 14, 19};

/* mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z:(i0[15],i1[15],i2,i3[5],i4[2])->(o0[20x15,55nz],o1[20x15,15nz],o2[20x1,1nz],o3[20x5,10nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=7.2115384615384617e+09;
  if (res[0]!=0) res[0][0]=a0;
  a0=-7.2115384615384617e+09;
  if (res[0]!=0) res[0][1]=a0;
  a1=2.0000000000000001e-01;
  a2=arg[4]? arg[4][0] : 0;
  a3=8.4823001646924400e+04;
  a4=arg[4]? arg[4][1] : 0;
  a5=(a3*a4);
  a5=(a2*a5);
  a5=(a1*a5);
  a5=(-a5);
  if (res[0]!=0) res[0][2]=a5;
  if (res[0]!=0) res[0][3]=a0;
  a5=1.4423076923076923e+10;
  if (res[0]!=0) res[0][4]=a5;
  if (res[0]!=0) res[0][5]=a0;
  a6=-8.4823001646924400e+04;
  a7=(a6*a4);
  a7=(a2*a7);
  a7=(a1*a7);
  a7=(-a7);
  if (res[0]!=0) res[0][6]=a7;
  a7=(a3*a4);
  a7=(a2*a7);
  a7=(a1*a7);
  a7=(-a7);
  if (res[0]!=0) res[0][7]=a7;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a5;
  if (res[0]!=0) res[0][10]=a0;
  a7=(a6*a4);
  a7=(a2*a7);
  a7=(a1*a7);
  a7=(-a7);
  if (res[0]!=0) res[0][11]=a7;
  a7=(a3*a4);
  a7=(a2*a7);
  a7=(a1*a7);
  a7=(-a7);
  if (res[0]!=0) res[0][12]=a7;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a5;
  if (res[0]!=0) res[0][15]=a0;
  a7=(a6*a4);
  a7=(a2*a7);
  a7=(a1*a7);
  a7=(-a7);
  if (res[0]!=0) res[0][16]=a7;
  a7=(a3*a4);
  a7=(a2*a7);
  a7=(a1*a7);
  a7=(-a7);
  if (res[0]!=0) res[0][17]=a7;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a5;
  a6=(a6*a4);
  a6=(a2*a6);
  a6=(a1*a6);
  a6=(-a6);
  if (res[0]!=0) res[0][20]=a6;
  a3=(a3*a4);
  a2=(a2*a3);
  a1=(a1*a2);
  a1=(-a1);
  if (res[0]!=0) res[0][21]=a1;
  a1=-1.;
  if (res[0]!=0) res[0][22]=a1;
  a2=8.5018666181568038e+06;
  if (res[0]!=0) res[0][23]=a2;
  a2=-8.5018666181568038e+06;
  if (res[0]!=0) res[0][24]=a2;
  a3=5500.;
  a4=1.;
  a6=arg[0]? arg[0][10] : 0;
  a5=arg[0]? arg[0][5] : 0;
  a0=casadi_sq(a5);
  a7=1.0000000000000000e-10;
  a0=(a0+a7);
  a0=sqrt(a0);
  a5=(a5/a0);
  a5=(a6*a5);
  a8=arg[3]? arg[3][0] : 0;
  a8=(a8+a7);
  a5=(a5/a8);
  a5=(a4-a5);
  a5=(a3*a5);
  a5=(-a5);
  if (res[0]!=0) res[0][25]=a5;
  if (res[0]!=0) res[0][26]=a1;
  if (res[0]!=0) res[0][27]=a2;
  a5=1.7003733236313608e+07;
  if (res[0]!=0) res[0][28]=a5;
  if (res[0]!=0) res[0][29]=a2;
  a9=arg[0]? arg[0][11] : 0;
  a10=arg[0]? arg[0][6] : 0;
  a11=casadi_sq(a10);
  a11=(a11+a7);
  a11=sqrt(a11);
  a10=(a10/a11);
  a10=(a9*a10);
  a12=arg[3]? arg[3][1] : 0;
  a12=(a12+a7);
  a10=(a10/a12);
  a10=(a4-a10);
  a10=(a3*a10);
  a10=(-a10);
  if (res[0]!=0) res[0][30]=a10;
  if (res[0]!=0) res[0][31]=a1;
  if (res[0]!=0) res[0][32]=a2;
  if (res[0]!=0) res[0][33]=a5;
  if (res[0]!=0) res[0][34]=a2;
  a10=arg[0]? arg[0][12] : 0;
  a13=arg[0]? arg[0][7] : 0;
  a14=casadi_sq(a13);
  a14=(a14+a7);
  a14=sqrt(a14);
  a13=(a13/a14);
  a13=(a10*a13);
  a15=arg[3]? arg[3][2] : 0;
  a15=(a15+a7);
  a13=(a13/a15);
  a13=(a4-a13);
  a13=(a3*a13);
  a13=(-a13);
  if (res[0]!=0) res[0][35]=a13;
  if (res[0]!=0) res[0][36]=a1;
  if (res[0]!=0) res[0][37]=a2;
  if (res[0]!=0) res[0][38]=a5;
  if (res[0]!=0) res[0][39]=a2;
  a13=arg[0]? arg[0][13] : 0;
  a16=arg[0]? arg[0][8] : 0;
  a17=casadi_sq(a16);
  a17=(a17+a7);
  a17=sqrt(a17);
  a16=(a16/a17);
  a16=(a13*a16);
  a18=arg[3]? arg[3][3] : 0;
  a18=(a18+a7);
  a16=(a16/a18);
  a16=(a4-a16);
  a16=(a3*a16);
  a16=(-a16);
  if (res[0]!=0) res[0][40]=a16;
  if (res[0]!=0) res[0][41]=a1;
  if (res[0]!=0) res[0][42]=a2;
  if (res[0]!=0) res[0][43]=a5;
  a5=arg[0]? arg[0][14] : 0;
  a2=arg[0]? arg[0][9] : 0;
  a1=casadi_sq(a2);
  a1=(a1+a7);
  a1=sqrt(a1);
  a2=(a2/a1);
  a2=(a5*a2);
  a16=arg[3]? arg[3][4] : 0;
  a16=(a16+a7);
  a2=(a2/a16);
  a2=(a4-a2);
  a2=(a3*a2);
  a2=(-a2);
  if (res[0]!=0) res[0][44]=a2;
  a2=8.5018666181568042e+04;
  if (res[0]!=0) res[0][45]=a2;
  a7=(a0/a8);
  a7=(a3*a7);
  if (res[0]!=0) res[0][46]=a7;
  if (res[0]!=0) res[0][47]=a2;
  a7=(a11/a12);
  a7=(a3*a7);
  if (res[0]!=0) res[0][48]=a7;
  if (res[0]!=0) res[0][49]=a2;
  a7=(a14/a15);
  a7=(a3*a7);
  if (res[0]!=0) res[0][50]=a7;
  if (res[0]!=0) res[0][51]=a2;
  a7=(a17/a18);
  a7=(a3*a7);
  if (res[0]!=0) res[0][52]=a7;
  if (res[0]!=0) res[0][53]=a2;
  a2=(a1/a16);
  a2=(a3*a2);
  if (res[0]!=0) res[0][54]=a2;
  if (res[1]!=0) res[1][0]=a4;
  if (res[1]!=0) res[1][1]=a4;
  if (res[1]!=0) res[1][2]=a4;
  if (res[1]!=0) res[1][3]=a4;
  if (res[1]!=0) res[1][4]=a4;
  if (res[1]!=0) res[1][5]=a4;
  if (res[1]!=0) res[1][6]=a4;
  if (res[1]!=0) res[1][7]=a4;
  if (res[1]!=0) res[1][8]=a4;
  if (res[1]!=0) res[1][9]=a4;
  if (res[1]!=0) res[1][10]=a4;
  if (res[1]!=0) res[1][11]=a4;
  if (res[1]!=0) res[1][12]=a4;
  if (res[1]!=0) res[1][13]=a4;
  if (res[1]!=0) res[1][14]=a4;
  a2=-8.5018666181568042e+04;
  if (res[2]!=0) res[2][0]=a2;
  a6=(a6*a0);
  a6=(a6/a8);
  a6=(a6/a8);
  a6=(a3*a6);
  a6=(-a6);
  if (res[3]!=0) res[3][0]=a6;
  if (res[3]!=0) res[3][1]=a4;
  a9=(a9*a11);
  a9=(a9/a12);
  a9=(a9/a12);
  a9=(a3*a9);
  a9=(-a9);
  if (res[3]!=0) res[3][2]=a9;
  if (res[3]!=0) res[3][3]=a4;
  a10=(a10*a14);
  a10=(a10/a15);
  a10=(a10/a15);
  a10=(a3*a10);
  a10=(-a10);
  if (res[3]!=0) res[3][4]=a10;
  if (res[3]!=0) res[3][5]=a4;
  a13=(a13*a17);
  a13=(a13/a18);
  a13=(a13/a18);
  a13=(a3*a13);
  a13=(-a13);
  if (res[3]!=0) res[3][6]=a13;
  if (res[3]!=0) res[3][7]=a4;
  a5=(a5*a1);
  a5=(a5/a16);
  a5=(a5/a16);
  a3=(a3*a5);
  a3=(-a3);
  if (res[3]!=0) res[3][8]=a3;
  if (res[3]!=0) res[3][9]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mass_spring_damper_friction_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
