/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) model_three_mass_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[59] = {7, 7, 0, 7, 14, 21, 28, 35, 42, 49, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};

/* model_three_mass_expl_vde_forw:(i0[7],i1[7x7],i2[7],i3,i4)->(o0[7],o1[7x7],o2[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a2;
  a3=arg[3]? arg[3][0] : 0;
  a4=3500.;
  a0=(a4*a0);
  a3=(a3-a0);
  a0=75400.;
  a5=arg[0]? arg[0][0] : 0;
  a6=arg[0]? arg[0][2] : 0;
  a7=(a5-a6);
  a7=(a0*a7);
  a3=(a3-a7);
  a7=2.;
  a3=(a3/a7);
  if (res[0]!=0) res[0][3]=a3;
  a3=-500.;
  a8=arg[0]? arg[0][1] : 0;
  a9=(a3*a8);
  a10=100.;
  a1=(a10*a1);
  a9=(a9-a1);
  a1=(a8-a6);
  a1=(a0*a1);
  a9=(a9-a1);
  a1=1.2999999999999999e-05;
  a9=(a9/a1);
  if (res[0]!=0) res[0][4]=a9;
  a9=arg[0]? arg[0][6] : 0;
  a1=1000.;
  a11=(a1*a2);
  a11=(a9-a11);
  a6=(a7*a6);
  a12=(a5+a8);
  a6=(a6-a12);
  a6=(a0*a6);
  a11=(a11-a6);
  a6=5.0000000000000003e-02;
  a11=(a11/a6);
  if (res[0]!=0) res[0][5]=a11;
  a11=1200.;
  a6=casadi_sq(a2);
  a12=1.0000000000000000e-10;
  a6=(a6+a12);
  a6=sqrt(a6);
  a12=(a9*a6);
  a13=4.5000000000000001e-01;
  a8=(a8-a5);
  a8=(a0*a8);
  a8=(a13*a8);
  a5=arg[4]? arg[4][0] : 0;
  a8=(a8*a5);
  a14=9.9999999999999995e-07;
  a8=(a8+a14);
  a12=(a12/a8);
  a14=(a2-a12);
  a14=(a11*a14);
  if (res[0]!=0) res[0][6]=a14;
  a14=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][0]=a14;
  a15=arg[1]? arg[1][4] : 0;
  if (res[1]!=0) res[1][1]=a15;
  a16=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][2]=a16;
  a17=5.0000000000000000e-01;
  a14=(a4*a14);
  a18=arg[1]? arg[1][0] : 0;
  a19=arg[1]? arg[1][2] : 0;
  a20=(a18-a19);
  a20=(a0*a20);
  a14=(a14+a20);
  a14=(a17*a14);
  a14=(-a14);
  if (res[1]!=0) res[1][3]=a14;
  a14=7.6923076923076922e+04;
  a20=arg[1]? arg[1][1] : 0;
  a21=(a3*a20);
  a15=(a10*a15);
  a21=(a21-a15);
  a15=(a20-a19);
  a15=(a0*a15);
  a21=(a21-a15);
  a21=(a14*a21);
  if (res[1]!=0) res[1][4]=a21;
  a21=20.;
  a15=arg[1]? arg[1][6] : 0;
  a22=(a1*a16);
  a22=(a15-a22);
  a19=(a7*a19);
  a23=(a18+a20);
  a19=(a19-a23);
  a19=(a0*a19);
  a22=(a22-a19);
  a22=(a21*a22);
  if (res[1]!=0) res[1][5]=a22;
  a15=(a6*a15);
  a22=(a2+a2);
  a19=(a22*a16);
  a23=(a6+a6);
  a19=(a19/a23);
  a19=(a9*a19);
  a15=(a15+a19);
  a15=(a15/a8);
  a19=(a12/a8);
  a20=(a20-a18);
  a20=(a0*a20);
  a20=(a13*a20);
  a20=(a5*a20);
  a20=(a19*a20);
  a15=(a15-a20);
  a16=(a16-a15);
  a16=(a11*a16);
  if (res[1]!=0) res[1][6]=a16;
  a16=arg[1]? arg[1][10] : 0;
  if (res[1]!=0) res[1][7]=a16;
  a15=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][8]=a15;
  a20=arg[1]? arg[1][12] : 0;
  if (res[1]!=0) res[1][9]=a20;
  a16=(a4*a16);
  a18=arg[1]? arg[1][7] : 0;
  a24=arg[1]? arg[1][9] : 0;
  a25=(a18-a24);
  a25=(a0*a25);
  a16=(a16+a25);
  a16=(a17*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][10]=a16;
  a16=arg[1]? arg[1][8] : 0;
  a25=(a3*a16);
  a15=(a10*a15);
  a25=(a25-a15);
  a15=(a16-a24);
  a15=(a0*a15);
  a25=(a25-a15);
  a25=(a14*a25);
  if (res[1]!=0) res[1][11]=a25;
  a25=arg[1]? arg[1][13] : 0;
  a15=(a1*a20);
  a15=(a25-a15);
  a24=(a7*a24);
  a26=(a18+a16);
  a24=(a24-a26);
  a24=(a0*a24);
  a15=(a15-a24);
  a15=(a21*a15);
  if (res[1]!=0) res[1][12]=a15;
  a25=(a6*a25);
  a15=(a22*a20);
  a15=(a15/a23);
  a15=(a9*a15);
  a25=(a25+a15);
  a25=(a25/a8);
  a16=(a16-a18);
  a16=(a0*a16);
  a16=(a13*a16);
  a16=(a5*a16);
  a16=(a19*a16);
  a25=(a25-a16);
  a20=(a20-a25);
  a20=(a11*a20);
  if (res[1]!=0) res[1][13]=a20;
  a20=arg[1]? arg[1][17] : 0;
  if (res[1]!=0) res[1][14]=a20;
  a25=arg[1]? arg[1][18] : 0;
  if (res[1]!=0) res[1][15]=a25;
  a16=arg[1]? arg[1][19] : 0;
  if (res[1]!=0) res[1][16]=a16;
  a20=(a4*a20);
  a18=arg[1]? arg[1][14] : 0;
  a15=arg[1]? arg[1][16] : 0;
  a24=(a18-a15);
  a24=(a0*a24);
  a20=(a20+a24);
  a20=(a17*a20);
  a20=(-a20);
  if (res[1]!=0) res[1][17]=a20;
  a20=arg[1]? arg[1][15] : 0;
  a24=(a3*a20);
  a25=(a10*a25);
  a24=(a24-a25);
  a25=(a20-a15);
  a25=(a0*a25);
  a24=(a24-a25);
  a24=(a14*a24);
  if (res[1]!=0) res[1][18]=a24;
  a24=arg[1]? arg[1][20] : 0;
  a25=(a1*a16);
  a25=(a24-a25);
  a15=(a7*a15);
  a26=(a18+a20);
  a15=(a15-a26);
  a15=(a0*a15);
  a25=(a25-a15);
  a25=(a21*a25);
  if (res[1]!=0) res[1][19]=a25;
  a24=(a6*a24);
  a25=(a22*a16);
  a25=(a25/a23);
  a25=(a9*a25);
  a24=(a24+a25);
  a24=(a24/a8);
  a20=(a20-a18);
  a20=(a0*a20);
  a20=(a13*a20);
  a20=(a5*a20);
  a20=(a19*a20);
  a24=(a24-a20);
  a16=(a16-a24);
  a16=(a11*a16);
  if (res[1]!=0) res[1][20]=a16;
  a16=arg[1]? arg[1][24] : 0;
  if (res[1]!=0) res[1][21]=a16;
  a24=arg[1]? arg[1][25] : 0;
  if (res[1]!=0) res[1][22]=a24;
  a20=arg[1]? arg[1][26] : 0;
  if (res[1]!=0) res[1][23]=a20;
  a16=(a4*a16);
  a18=arg[1]? arg[1][21] : 0;
  a25=arg[1]? arg[1][23] : 0;
  a15=(a18-a25);
  a15=(a0*a15);
  a16=(a16+a15);
  a16=(a17*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][24]=a16;
  a16=arg[1]? arg[1][22] : 0;
  a15=(a3*a16);
  a24=(a10*a24);
  a15=(a15-a24);
  a24=(a16-a25);
  a24=(a0*a24);
  a15=(a15-a24);
  a15=(a14*a15);
  if (res[1]!=0) res[1][25]=a15;
  a15=arg[1]? arg[1][27] : 0;
  a24=(a1*a20);
  a24=(a15-a24);
  a25=(a7*a25);
  a26=(a18+a16);
  a25=(a25-a26);
  a25=(a0*a25);
  a24=(a24-a25);
  a24=(a21*a24);
  if (res[1]!=0) res[1][26]=a24;
  a15=(a6*a15);
  a24=(a22*a20);
  a24=(a24/a23);
  a24=(a9*a24);
  a15=(a15+a24);
  a15=(a15/a8);
  a16=(a16-a18);
  a16=(a0*a16);
  a16=(a13*a16);
  a16=(a5*a16);
  a16=(a19*a16);
  a15=(a15-a16);
  a20=(a20-a15);
  a20=(a11*a20);
  if (res[1]!=0) res[1][27]=a20;
  a20=arg[1]? arg[1][31] : 0;
  if (res[1]!=0) res[1][28]=a20;
  a15=arg[1]? arg[1][32] : 0;
  if (res[1]!=0) res[1][29]=a15;
  a16=arg[1]? arg[1][33] : 0;
  if (res[1]!=0) res[1][30]=a16;
  a20=(a4*a20);
  a18=arg[1]? arg[1][28] : 0;
  a24=arg[1]? arg[1][30] : 0;
  a25=(a18-a24);
  a25=(a0*a25);
  a20=(a20+a25);
  a20=(a17*a20);
  a20=(-a20);
  if (res[1]!=0) res[1][31]=a20;
  a20=arg[1]? arg[1][29] : 0;
  a25=(a3*a20);
  a15=(a10*a15);
  a25=(a25-a15);
  a15=(a20-a24);
  a15=(a0*a15);
  a25=(a25-a15);
  a25=(a14*a25);
  if (res[1]!=0) res[1][32]=a25;
  a25=arg[1]? arg[1][34] : 0;
  a15=(a1*a16);
  a15=(a25-a15);
  a24=(a7*a24);
  a26=(a18+a20);
  a24=(a24-a26);
  a24=(a0*a24);
  a15=(a15-a24);
  a15=(a21*a15);
  if (res[1]!=0) res[1][33]=a15;
  a25=(a6*a25);
  a15=(a22*a16);
  a15=(a15/a23);
  a15=(a9*a15);
  a25=(a25+a15);
  a25=(a25/a8);
  a20=(a20-a18);
  a20=(a0*a20);
  a20=(a13*a20);
  a20=(a5*a20);
  a20=(a19*a20);
  a25=(a25-a20);
  a16=(a16-a25);
  a16=(a11*a16);
  if (res[1]!=0) res[1][34]=a16;
  a16=arg[1]? arg[1][38] : 0;
  if (res[1]!=0) res[1][35]=a16;
  a25=arg[1]? arg[1][39] : 0;
  if (res[1]!=0) res[1][36]=a25;
  a20=arg[1]? arg[1][40] : 0;
  if (res[1]!=0) res[1][37]=a20;
  a16=(a4*a16);
  a18=arg[1]? arg[1][35] : 0;
  a15=arg[1]? arg[1][37] : 0;
  a24=(a18-a15);
  a24=(a0*a24);
  a16=(a16+a24);
  a16=(a17*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][38]=a16;
  a16=arg[1]? arg[1][36] : 0;
  a24=(a3*a16);
  a25=(a10*a25);
  a24=(a24-a25);
  a25=(a16-a15);
  a25=(a0*a25);
  a24=(a24-a25);
  a24=(a14*a24);
  if (res[1]!=0) res[1][39]=a24;
  a24=arg[1]? arg[1][41] : 0;
  a25=(a1*a20);
  a25=(a24-a25);
  a15=(a7*a15);
  a26=(a18+a16);
  a15=(a15-a26);
  a15=(a0*a15);
  a25=(a25-a15);
  a25=(a21*a25);
  if (res[1]!=0) res[1][40]=a25;
  a24=(a6*a24);
  a25=(a22*a20);
  a25=(a25/a23);
  a25=(a9*a25);
  a24=(a24+a25);
  a24=(a24/a8);
  a16=(a16-a18);
  a16=(a0*a16);
  a16=(a13*a16);
  a16=(a5*a16);
  a16=(a19*a16);
  a24=(a24-a16);
  a20=(a20-a24);
  a20=(a11*a20);
  if (res[1]!=0) res[1][41]=a20;
  a20=arg[1]? arg[1][45] : 0;
  if (res[1]!=0) res[1][42]=a20;
  a24=arg[1]? arg[1][46] : 0;
  if (res[1]!=0) res[1][43]=a24;
  a16=arg[1]? arg[1][47] : 0;
  if (res[1]!=0) res[1][44]=a16;
  a20=(a4*a20);
  a18=arg[1]? arg[1][42] : 0;
  a25=arg[1]? arg[1][44] : 0;
  a15=(a18-a25);
  a15=(a0*a15);
  a20=(a20+a15);
  a20=(a17*a20);
  a20=(-a20);
  if (res[1]!=0) res[1][45]=a20;
  a20=arg[1]? arg[1][43] : 0;
  a15=(a3*a20);
  a24=(a10*a24);
  a15=(a15-a24);
  a24=(a20-a25);
  a24=(a0*a24);
  a15=(a15-a24);
  a15=(a14*a15);
  if (res[1]!=0) res[1][46]=a15;
  a15=arg[1]? arg[1][48] : 0;
  a24=(a1*a16);
  a24=(a15-a24);
  a25=(a7*a25);
  a26=(a18+a20);
  a25=(a25-a26);
  a25=(a0*a25);
  a24=(a24-a25);
  a24=(a21*a24);
  if (res[1]!=0) res[1][47]=a24;
  a15=(a6*a15);
  a22=(a22*a16);
  a22=(a22/a23);
  a22=(a9*a22);
  a15=(a15+a22);
  a15=(a15/a8);
  a20=(a20-a18);
  a20=(a0*a20);
  a20=(a13*a20);
  a20=(a5*a20);
  a19=(a19*a20);
  a15=(a15-a19);
  a16=(a16-a15);
  a16=(a11*a16);
  if (res[1]!=0) res[1][48]=a16;
  a16=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][0]=a16;
  a15=arg[2]? arg[2][4] : 0;
  if (res[2]!=0) res[2][1]=a15;
  a19=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][2]=a19;
  a4=(a4*a16);
  a16=arg[2]? arg[2][0] : 0;
  a20=arg[2]? arg[2][2] : 0;
  a18=(a16-a20);
  a18=(a0*a18);
  a4=(a4+a18);
  a4=(a17*a4);
  a17=(a17-a4);
  if (res[2]!=0) res[2][3]=a17;
  a17=arg[2]? arg[2][1] : 0;
  a3=(a3*a17);
  a10=(a10*a15);
  a3=(a3-a10);
  a10=(a17-a20);
  a10=(a0*a10);
  a3=(a3-a10);
  a14=(a14*a3);
  if (res[2]!=0) res[2][4]=a14;
  a14=arg[2]? arg[2][6] : 0;
  a1=(a1*a19);
  a1=(a14-a1);
  a7=(a7*a20);
  a20=(a16+a17);
  a7=(a7-a20);
  a7=(a0*a7);
  a1=(a1-a7);
  a21=(a21*a1);
  if (res[2]!=0) res[2][5]=a21;
  a14=(a6*a14);
  a2=(a2+a2);
  a2=(a2*a19);
  a6=(a6+a6);
  a2=(a2/a6);
  a9=(a9*a2);
  a14=(a14+a9);
  a14=(a14/a8);
  a12=(a12/a8);
  a17=(a17-a16);
  a0=(a0*a17);
  a13=(a13*a0);
  a5=(a5*a13);
  a12=(a12*a5);
  a14=(a14-a12);
  a19=(a19-a14);
  a11=(a11*a19);
  if (res[2]!=0) res[2][6]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int model_three_mass_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int model_three_mass_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int model_three_mass_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_three_mass_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int model_three_mass_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void model_three_mass_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void model_three_mass_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void model_three_mass_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int model_three_mass_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int model_three_mass_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real model_three_mass_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_three_mass_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* model_three_mass_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_three_mass_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* model_three_mass_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int model_three_mass_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
