/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s3[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s4[28] = {8, 6, 0, 3, 7, 11, 15, 17, 19, 2, 3, 6, 2, 3, 6, 7, 0, 2, 3, 4, 1, 2, 3, 5, 2, 4, 3, 5};
static const casadi_int casadi_s5[15] = {8, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s6[5] = {8, 1, 0, 1, 2};
static const casadi_int casadi_s7[9] = {8, 2, 0, 2, 4, 4, 6, 5, 7};

/* mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z:(i0[6],i1[6],i2,i3[2],i4[2])->(o0[8],o1[8x6,19nz],o2[8x6,6nz],o3[8x1,1nz],o4[8x2,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a2=arg[0]? arg[0][3] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a3=7.6516799563411230e+04;
  a4=-100.;
  a4=(a4*a1);
  a5=100.;
  a6=(a5*a2);
  a4=(a4+a6);
  a6=arg[2]? arg[2][0] : 0;
  a7=3.7699111843077517e+04;
  a8=arg[0]? arg[0][0] : 0;
  a9=(a7*a8);
  a10=-3.7699111843077517e+04;
  a11=arg[0]? arg[0][1] : 0;
  a12=(a10*a11);
  a9=(a9+a12);
  a6=(a6-a9);
  a4=(a4+a6);
  a6=arg[0]? arg[0][4] : 0;
  a4=(a4-a6);
  a4=(a3*a4);
  a0=(a0-a4);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a5=(a5*a1);
  a4=-200.;
  a4=(a4*a2);
  a5=(a5+a4);
  a4=(a7*a11);
  a9=(a9-a4);
  a5=(a5+a9);
  a9=arg[0]? arg[0][5] : 0;
  a5=(a5-a9);
  a5=(a3*a5);
  a0=(a0-a5);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a5=7500000.;
  a4=casadi_sq(a1);
  a12=1.0000000000000000e-10;
  a4=(a4+a12);
  a4=sqrt(a4);
  a13=(a6*a4);
  a14=arg[3]? arg[3][0] : 0;
  a15=1.0000000000000000e-08;
  a16=(a14+a15);
  a13=(a13/a16);
  a17=(a1-a13);
  a17=(a5*a17);
  a0=(a0-a17);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][5] : 0;
  a17=casadi_sq(a2);
  a17=(a17+a12);
  a17=sqrt(a17);
  a12=(a9*a17);
  a18=arg[3]? arg[3][1] : 0;
  a15=(a18+a15);
  a12=(a12/a15);
  a19=(a2-a12);
  a19=(a5*a19);
  a0=(a0-a19);
  if (res[0]!=0) res[0][5]=a0;
  a8=(a8-a11);
  a8=(a7*a8);
  a0=arg[4]? arg[4][1] : 0;
  a8=(a8*a0);
  a19=arg[4]? arg[4][0] : 0;
  a8=(a8*a19);
  a20=2.;
  a8=(a8/a20);
  a14=(a14-a8);
  if (res[0]!=0) res[0][6]=a14;
  a11=(a7*a11);
  a11=(a11*a0);
  a11=(a11*a19);
  a11=(a11/a20);
  a18=(a18-a11);
  if (res[0]!=0) res[0][7]=a18;
  a18=2.8846153846153851e+09;
  if (res[1]!=0) res[1][0]=a18;
  a18=-2.8846153846153851e+09;
  if (res[1]!=0) res[1][1]=a18;
  a11=5.0000000000000000e-01;
  a20=(a7*a0);
  a20=(a19*a20);
  a20=(a11*a20);
  a20=(-a20);
  if (res[1]!=0) res[1][2]=a20;
  if (res[1]!=0) res[1][3]=a18;
  a18=5.7692307692307701e+09;
  if (res[1]!=0) res[1][4]=a18;
  a10=(a10*a0);
  a10=(a19*a10);
  a10=(a11*a10);
  a10=(-a10);
  if (res[1]!=0) res[1][5]=a10;
  a7=(a7*a0);
  a19=(a19*a7);
  a11=(a11*a19);
  a11=(-a11);
  if (res[1]!=0) res[1][6]=a11;
  a11=-1.;
  if (res[1]!=0) res[1][7]=a11;
  a19=7.6516799563411232e+06;
  if (res[1]!=0) res[1][8]=a19;
  a19=-7.6516799563411232e+06;
  if (res[1]!=0) res[1][9]=a19;
  a7=1.;
  a1=(a1/a4);
  a6=(a6*a1);
  a6=(a6/a16);
  a6=(a7-a6);
  a6=(a5*a6);
  a6=(-a6);
  if (res[1]!=0) res[1][10]=a6;
  if (res[1]!=0) res[1][11]=a11;
  if (res[1]!=0) res[1][12]=a19;
  a19=1.5303359912682246e+07;
  if (res[1]!=0) res[1][13]=a19;
  a2=(a2/a17);
  a9=(a9*a2);
  a9=(a9/a15);
  a9=(a7-a9);
  a9=(a5*a9);
  a9=(-a9);
  if (res[1]!=0) res[1][14]=a9;
  if (res[1]!=0) res[1][15]=a3;
  a4=(a4/a16);
  a4=(a5*a4);
  if (res[1]!=0) res[1][16]=a4;
  if (res[1]!=0) res[1][17]=a3;
  a17=(a17/a15);
  a17=(a5*a17);
  if (res[1]!=0) res[1][18]=a17;
  if (res[2]!=0) res[2][0]=a7;
  if (res[2]!=0) res[2][1]=a7;
  if (res[2]!=0) res[2][2]=a7;
  if (res[2]!=0) res[2][3]=a7;
  if (res[2]!=0) res[2][4]=a7;
  if (res[2]!=0) res[2][5]=a7;
  a17=-7.6516799563411230e+04;
  if (res[3]!=0) res[3][0]=a17;
  a13=(a13/a16);
  a13=(a5*a13);
  a13=(-a13);
  if (res[4]!=0) res[4][0]=a13;
  if (res[4]!=0) res[4][1]=a7;
  a12=(a12/a15);
  a5=(a5*a12);
  a5=(-a5);
  if (res[4]!=0) res[4][2]=a5;
  if (res[4]!=0) res[4][3]=a7;
  return 0;
}

CASADI_SYMBOL_EXPORT int mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mass_spring_damper_friction_impl_dae_fun_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
